id: exposed-sharepoint-list.asmx

info:
  name: Exposed sharepoint list
  author: @ELSFA7110
  severity: low
  reference: https://hackerone.com/reports/761158
             https://hackerone.com/reports/300539
  tags: config,exposure

requests:
  - method: GET
    path:
      - "{{BaseURL}}/_vti_bin/lists.asmx?WSDL"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "GetListResponse"
        part: body

      - type: status
        status:
          - 200
